const END_POINT = "https://henry-little-world.herokuapp.com/api";
const USER = "auth";
const PORTFOLIOS = "portfolios";
const LEET_CODES = "leet-codes";
const APPLICATIONS = "applications";
const COMPONENTS = "components";
const FAVORITE = "favorites";
const BULLETINBOARD = "bulletin-boards";
const QUICK_LINKS = "quick-links";

const apiMatrix = {
  //User
  USER_REGISTER: `${END_POINT}/${USER}/local/register`,
  USER_LOGIN: `${END_POINT}/${USER}/local`,
  USER_CHANGE_PASSWORD: `${END_POINT}/${USER}/change-password`,
  //Portfolio
  PORTFOLIOS_GET_ALL: `${END_POINT}/${PORTFOLIOS}`,
  PORTFOLIOS_GET_BY_ID: `${END_POINT}/${PORTFOLIOS}`, // /ID
  PORTFOLIOS_CREATE_NEW: `${END_POINT}/${PORTFOLIOS}`,
  PORTFOLIOS_DELETE_BY_ID: `${END_POINT}/${PORTFOLIOS}`, // /ID
  PORTFOLIOS_UPDATE_BY_ID: `${END_POINT}/${PORTFOLIOS}`, // /ID
  //Leet-code
  LEET_CODES_GET_ALL: `${END_POINT}/${LEET_CODES}`,
  LEET_CODES_GET_BY_ID: `${END_POINT}/${LEET_CODES}`, // /ID
  LEET_CODES_CREATE_NEW: `${END_POINT}/${LEET_CODES}`,
  LEET_CODES_DELETE_BY_ID: `${END_POINT}/${LEET_CODES}`, // /ID
  LEET_CODES_UPDATE_BY_ID: `${END_POINT}/${LEET_CODES}`, // /ID
  //Application
  APPLICATIONS_GET_ALL: `${END_POINT}/${APPLICATIONS}`,
  APPLICATIONS_GET_BY_ID: `${END_POINT}/${APPLICATIONS}`, // /ID
  APPLICATIONS_CREATE_NEW: `${END_POINT}/${APPLICATIONS}`,
  APPLICATIONS_DELETE_BY_ID: `${END_POINT}/${APPLICATIONS}`, // /ID
  APPLICATIONS_UPDATE_BY_ID: `${END_POINT}/${APPLICATIONS}`, // /ID
  //Component
  COMPONENTS_GET_ALL: `${END_POINT}/${COMPONENTS}`,
  COMPONENTS_GET_BY_ID: `${END_POINT}/${COMPONENTS}`, // /ID
  COMPONENTS_CREATE_NEW: `${END_POINT}/${COMPONENTS}`,
  COMPONENTS_DELETE_BY_ID: `${END_POINT}/${COMPONENTS}`, // /ID
  COMPONENTS_UPDATE_BY_ID: `${END_POINT}/${COMPONENTS}`, // /ID
  //Favorite
  FAVORITE_GET_ALL: `${END_POINT}/${FAVORITE}`,
  FAVORITE_GET_BY_ID: `${END_POINT}/${FAVORITE}`, // /ID
  FAVORITE_CREATE_NEW: `${END_POINT}/${FAVORITE}`,
  FAVORITE_DELETE_BY_ID: `${END_POINT}/${FAVORITE}`, // /ID
  FAVORITE_UPDATE_BY_ID: `${END_POINT}/${FAVORITE}`, // /ID
  //Bulletin Board
  BULLETINBOARD_GET_ALL: `${END_POINT}/${BULLETINBOARD}`,
  BULLETINBOARD_GET_BY_ID: `${END_POINT}/${BULLETINBOARD}`, // /ID
  BULLETINBOARD_CREATE_NEW: `${END_POINT}/${BULLETINBOARD}`,
  BULLETINBOARD_DELETE_BY_ID: `${END_POINT}/${BULLETINBOARD}`, // /ID
  BULLETINBOARD_UPDATE_BY_ID: `${END_POINT}/${BULLETINBOARD}`, // /ID
  //Quick Links
  QUICK_LINKS_GET_ALL: `${END_POINT}/${QUICK_LINKS}`,
  QUICK_LINKS_GET_BY_ID: `${END_POINT}/${QUICK_LINKS}`, // /ID
  QUICK_LINKS_CREATE_NEW: `${END_POINT}/${QUICK_LINKS}`,
  QUICK_LINKS_DELETE_BY_ID: `${END_POINT}/${QUICK_LINKS}`, // /ID
  QUICK_LINKS_UPDATE_BY_ID: `${END_POINT}/${QUICK_LINKS}`, // /ID
};

export default apiMatrix;
