const END_POINT = "https://henry-little-world.herokuapp.com/api";
const PORTFOLIOS = "portfolios";
const LEET_CODES = "leet-codes";
const APPLICATIONS = "applications";

const apiMatrix = {
  //Portfolio
  PORTFOLIOS_GET_ALL: `${END_POINT}/${PORTFOLIOS}`,
  PORTFOLIOS_GET_BY_ID: `${END_POINT}/${PORTFOLIOS}`, // /ID
  PORTFOLIOS_CREATE_NEW: `${END_POINT}/${PORTFOLIOS}`,
  PORTFOLIOS_DELETE_BY_ID: `${END_POINT}/${PORTFOLIOS}`, // /ID
  PORTFOLIOS_UPDATE_BY_ID: `${END_POINT}/${PORTFOLIOS}`, // /ID
  //Leet-code
  LEET_CODES_GET_ALL: `${END_POINT}/${LEET_CODES}`,
  LEET_CODES_GET_BY_ID: `${END_POINT}/${LEET_CODES}`, // /ID
  LEET_CODES_CREATE_NEW: `${END_POINT}/${LEET_CODES}`,
  LEET_CODES_DELETE_BY_ID: `${END_POINT}/${LEET_CODES}`, // /ID
  LEET_CODES_UPDATE_BY_ID: `${END_POINT}/${LEET_CODES}`, // /ID
  //Application
  APPLICATIONS_GET_ALL: `${END_POINT}/${APPLICATIONS}`,
  APPLICATIONS_GET_BY_ID: `${END_POINT}/${APPLICATIONS}`, // /ID
  APPLICATIONS_CREATE_NEW: `${END_POINT}/${APPLICATIONS}`,
  APPLICATIONS_DELETE_BY_ID: `${END_POINT}/${APPLICATIONS}`, // /ID
  APPLICATIONS_UPDATE_BY_ID: `${END_POINT}/${APPLICATIONS}`, // /ID
};

export default apiMatrix;
