const SET_CLICKED_HOME_PAGE_ITEM_ID = 'SET_CLICKED_HOME_PAGE_ITEM_ID';
const SET_PORTFOLIO_DATA = 'SET_PORTFOLIO_DATA';
const SET_EDIT_PORTFOLIO_ID = 'SET_EDIT_PORTFOLIO_ID'

export { SET_CLICKED_HOME_PAGE_ITEM_ID, SET_PORTFOLIO_DATA, SET_EDIT_PORTFOLIO_ID }