const SET_CLICKED_HOME_PAGE_ITEM_ID = "SET_CLICKED_HOME_PAGE_ITEM_ID";
const SET_PORTFOLIO_DATA = "SET_PORTFOLIO_DATA";
const SET_EDIT_PORTFOLIO_ID = "SET_EDIT_PORTFOLIO_ID";
const SET_LEETCODE_DATA = "SET_LEETCODE_DATA";
const SET_EDIT_LEETCODE_ID = "SET_EDIT_LEETCODE_ID";

export {
    SET_CLICKED_HOME_PAGE_ITEM_ID,
    SET_PORTFOLIO_DATA,
    SET_EDIT_PORTFOLIO_ID,
    SET_LEETCODE_DATA,
    SET_EDIT_LEETCODE_ID
};
